#!/bin/bash

defaults write com.apple.finder AppleShowAllFiles TRUE
killall Finder

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

brew cask install google-chrome
brew cask install visual-studio-code
brew cask install android-studio
brew cask install iterm2
brew cask install rectangle
brew install git
brew install node
brew install yarn
