#!/bin/bash

defaults write com.apple.finder AppleShowAllFiles TRUE
killall Finder

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install node git

brew tap homebrew/cask
brew cask install google-chrome visual-studio-code iterm2 spectacle

touch ~/.bash_profile
echo alias ls=\"ls -Ga\" >> ~/.bash_profile
echo alias ll=\"ls -l\" >> ~/.bash_profile

trimforce enable
