#!/bin/sh

DEV_USB_PATH=/dev/bus/usb
UAS_IDS=()
USB_STORAGE_CONF=/etc/modprobe.d/usbStorage.conf

DEV_USB_PATH=$(readlink -f $DEV_USB_PATH)"/"
for usb in $(find $DEV_USB_PATH -type c); do
  if [[ $(lsusb -D $usb | grep -i "uas") ]]; then
     IFS="/"
     read BUS DEV <<< "${usb/$DEV_USB_PATH/}"
     pattern="Bus $BUS Device $DEV: ID "
     match=$(lsusb | grep $pattern)
     match=${match/$pattern/}
     UAS_IDS+=($(echo $match | cut -d' ' -f1))
     unset IFS
  fi
done

rm -rf $USB_STORAGE_CONF
for id in "${UAS_IDS[@]}"; do
  echo options usb-storage quirks=$id:u >> $USB_STORAGE_CONF
done

dracut --force
