#!/bin/bash

yum groupinstall -y "X Window System"
yum install -y gnome-classic-session gnome-terminal liberation-fonts

systemctl set-default graphical.target

sh -c 'echo -e "[google-chrome]\nname=google-chrome\nbaseurl=https://dl.google.com/linux/chrome/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\ngpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub" > /etc/yum.repos.d/google-chrome.repo'
yum install -y google-chrome-stable
