#!/bin/bash

docker pull certbot/certbot

docker run -it
  --rm \
  -v /etc/letsencrypt:/etc/letsencrypt \
  certbot/certbot \
    certonly \
    --agree-tos \
    --register-unsafely-without-email \
    --server https://acme-v02.api.letsencrypt.org/directory
    --manual \
    --preferred-challenges dns \
    -d $1 \
    -d *.$1
